#!/bin/bash

# shell script to include dependencies need (listed in README.md)
# needs to be in ubuntu before running this

# stops on error, print commands
set -Eeuo pipefail
set -x

# install python 3.7
sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7

# install pip in ubuntu
sudo apt-get update
sudo apt-get install python3-pip
pip3 install --upgrade pip