runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -w 2 flask_app:app
runtime_config:
    python_version: 3.7
env_variables:
    CLOUD_STORAGE_BUCKET: tensorflow-serving-9905
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 50