apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: st-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: st-server
        spec:
            containers:
              - name: st-container
                image: gcr.io/tensorflow-serving-9905/st:monet
                ports:
                 - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
    labels:
        run: st-service
    name: st-service
spec:
    ports:
      - port: 8501
        targetPort: 8501
    selector:
        app: st-server
    type: LoadBalancer


    