apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: st-ske-deployment
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: st-ske-service
        spec:
            containers:
              - name: st-container
                image: gcr.io/tensorflow-serving-9905/servable:latest
                ports:
                 - containerPort: 8501
                 - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
    labels:
        run: st-ske-service
    name: st-ske-service
spec:
    ports:
      - port: 8501
        name: grpc
        targetPort: 8501
      - port: 8500
        name: rest
        targetPort: 8500
    selector:
        app: st-ske-service
    type: LoadBalancer
